<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Rimisekai</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>RimisekaiCore</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
